### ISSUE TITLE
Intento de subida en heroku

### ISSUE THREAD

**Issue by xleninx** [julianduque/animate-server#1]
Hola @julianduque , 

Primero que nada gracias por ser tan buen profesor tus clases están increíbles.

Te cuento, estoy intentando subir el app de animate-server a heroku pero me encontré con el siguiente problema:

```
at Error (native)
 events.js:141
       throw er; // Unhandled 'error' event
       ^
 Error: ENOENT: no such file or directory, open '/tmp/1cdec0b9-965f-4aab-a41b-fb4b80940604.webm'
```

Se que heroku no provee almacenamiento para sus aplicaciones y creo que no podre guardar el video dentro de su carpeta temporal, pero ahora me pregunto si sera posible guardarla en otro sitio o utilizar otro hosting para subir este app.

Gracias saludos.

**Comment by julianduque** [comment]
Depronto puedes modificar para que almacene en s3 pero esto tomaria mucho tiempo de subida y bajada del video, lo otro es probar en process.cwd() en vez de os.tmpDir()

**Comment by xleninx** [comment]
También probé con process.cwd() pero aun nada. Entiendo que heroku no soporta almacenar files en el server, pero he hecho apps en rails en donde se almacenan por un cierto tiempo los uploads files. 

Gracias por tu ayuda, seguiré intentando y si encuentro la solución te la comento.
