### ISSUE TITLE
Error al intentar iniciar el servidor

### ISSUE THREAD

**Issue by kathcode** [julianduque/animate-server#3]
Hola, @julianduque  me tengo este error que me sale despues de ingresar _npm start_, me puedes decir mas o menos que podría ser?
Gracias

$ npm start
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Catalina\Documents\proyects-All\chatEcample\npm-debug.log

**Comment by julianduque** [comment]
Hola @LeslieMeneses, fijate si en el archivo package.json esta el script `start` definido... Estas ejecutando un paso en particular o estas corriendo master?

**Comment by kathcode** [comment]
Hola @julianduque, si esta:
 "scripts": {
    "start": "node server.js"
  },
Yo clone el repositorio.

**Comment by julianduque** [comment]
@LeslieMeneses ya solucionamos este issue por el chat :)

**Comment by kathcode** [comment]
Gracias!! ;) @julianduque

**Comment by pedrolarap** [comment]
Buenas noches, podrían compartir como resolvieron ese problema.

**Comment by julianduque** [comment]
@pedrolarap si no estoy mas se estaba ejecutando el comando en el directorio equivocado

**Comment by josmorava** [comment]
@julianduque disculpa tengo un error parecido en mi consola al momento de ejecutar un script llamado 'dev', ¿podrías ayudarme a solucionarlo?, ¿como solucionaron este inconveniente?. Estuve revisando y estoy en la ruta raíz correcta.
